development:
  stripe_secret_key: 'sk_test_51HdymhESz0WxXwCaQNryOB73f9ltFexev1vzYjbkGL1ppf9sQVoEBWDinhsLzss4sdaW7nznB3jYIxWgcmUU2KPk00f2KG9B1c'
  stripe_publishable_key: 'pk_test_51HdymhESz0WxXwCaKTj5Ta4N8RPPEubgjDpOa2Y4hZY8ZMnstlzlQKikIzZfMVYBt4iRRS0ehrPDSHC4OXfpVwQC00Y1LZS9bm'
